services:
  # Next.js 应用
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    env_file:
      - .env.docker.local
    extra_hosts:
      # 允许容器访问宿主机上的服务
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge
